### ISSUE TITLE
File input values

### ISSUE THREAD

**Issue by wildtv** [glhd/aire-bootstrap#9]
Seems that the custom styling added for file inputs prevents the selected filepath from being visible after a selection.
Appears this is done to hide the choose button in favor of the right browse button.
Could you append the label with the file path after selection or something similar by default?

**Comment by amberlampsio** [comment]
@wildtv hey, can you show me a screen shot, I tried to replicate this without luck!

We will fix this as soon as I see the the bug

**Comment by wildtv** [comment]
Maybe it's something to do with other styles I've got going on.
The .custom-file-input class appears to disable the opacity of the text of the file path.
It would appear that's been done to hide the normal browse button, but takes the text as a side effect.  At least in Windows Chrome.

![noopacity](https://user-images.githubusercontent.com/53831978/106807263-2e821700-6626-11eb-8484-3ed399aebe3d.jpg)
![opacity](https://user-images.githubusercontent.com/53831978/106807274-317d0780-6626-11eb-9145-0d3769165302.JPG)

**Comment by amberlampsio** [comment]
@wildtv We are using the custom-file class for file upload from bootstrap, as shown here, 

https://getbootstrap.com/docs/4.0/components/forms/#file-browser

Code responsible for setting this, 
https://github.com/glhd/aire-bootstrap/blob/master/src/AireBootstrapServiceProvider.php#L145

**Comment by wildtv** [comment]
Not your problem, doesn't work in that example either, you'd think after this many years the file input would have been sorted out by now. :)
I'll custom class it myself in time. Thanks for the look.
